Feat/add user task associations and checkbox
bvakh-cybercraft/SOW-for-Ruby-on-Rails pull request #14
Opened 2024-01-31 22:16 UTC by bvakh-cybercraft

2024-01-31 22:25 UTC, bvakh-cybercraft commented on app/views/tasks/update.js.erb
> +var taskId = <%= @task.id %>;
Вчора дуже довго з цим розбирався, в результаті все рівно вийшло не те що очікував. Де я повернув не туди? Може маєш якісь матеріали які я б міг використати для прикладу, щоб таки зробити це завдання (статті, відео і т.п)

2024-02-01 08:25 UTC, proman-cybercraft requested changes

2024-02-01 08:25 UTC, proman-cybercraft commented on app/controllers/tasks_controller.rb
> +      @task.save
you already have .update method so you don't need to call .save

2024-02-01 08:25 UTC, proman-cybercraft commented on app/controllers/tasks_controller.rb
> +    redirect_to root_path, alert: "Access is denied. You are not the author of this task." unless @task.user == current_user
add `return` to avoid double render error
`return redirect_to......`

2024-02-01 08:25 UTC, proman-cybercraft commented on app/models/user.rb
> +  has_many :tasks
need to add dependent

2024-02-01 10:31 UTC, proman-cybercraft approved these changes

2024-02-06 08:34 UTC, proman-cybercraft approved these changes

2024-02-06 08:35 UTC, merged